Configure AM17 logging
artefactual-labs/ansible-role-archivematica-src pull request #167
Opened 2018-01-31 11:37 UTC by mamedin

A new option to configure backward-compatible logging has been added to
substitute the new AM17 logging setup. The default AM17 logging sends
the events to the standard streams, which is more convenient when
Archivematica is running in a cluster.

In order to use the backward-compatible logging, the boolean environment
variable 'archivematica_src_logging_backward_compatible' has to be
enabled, which is the default behaviour.

The log directory paths and log file sizes are configurable for each
service.

Fixes #147.

2018-01-31 12:31 UTC, scollazo requested changes
Readability changes suggested

2018-01-31 12:31 UTC, scollazo commented on defaults/main.yml
> +archivematica_src_dashboard_log_path: "/var/log/archivematica/dashboard"
This is confusing, the log path is `/var/log/archivematica/MCPCLient/MCPClient.log` , may be we can find a better name for this setting? ( `archivematica_src_dashboard_logdir`?)

2018-01-31 12:31 UTC, scollazo commented on defaults/main.yml
> +archivematica_src_dashboard_log_debug_maxbytes: "104857600"
A comment indicating the size in bytes/megabytes would come handy here

2018-01-31 14:01 UTC, mamedin commented
Thanks Santi for your suggestions 👍 

I have changed the PR, and it is ready for CR again.

2018-01-31 16:46 UTC, scollazo approved these changes
LGTM!

2018-02-05 16:44 UTC, sevein approved these changes

2018-02-05 17:35 UTC, merged