Allow for indexless installs
artefactual-labs/ansible-role-archivematica-src pull request #171
Opened 2018-02-06 15:34 UTC by scollazo

This adds the ARCHIVEMATICA_<service>_SEARCH_ENABLED env var

2018-02-06 15:46 UTC, scollazo commented
This is needed by artefactual/deploy-pub#52

2018-02-06 16:50 UTC, sevein requested changes
Can we add a note to the README? LGTM.

2018-02-06 18:56 UTC, jrwdunham approved these changes
Yes, with mention in the README this looks good to me.

2018-02-07 09:46 UTC, scollazo commented
Updated README to tell about the new `archivematica_src_search_enabled` var, and to point to the README.md files in archivematica.git

2018-02-07 14:37 UTC, sevein commented on README.md
> +Disable ElasticSearch use
`s/ElasticSearch/Elasticsearch`

2018-02-07 14:38 UTC, sevein commented on README.md
> +The default Archivematica install relies on ElasticSearch for different features (Archival storage, Backlog and Appraisal tabs). If you need to disable them, the boolean environment variable `archive
Nitpick: `archivematica_src_search_enabled` isn't an environment variable. Role variable?

2018-02-12 00:00 UTC, jrwdunham commented
@sevein What do you think? Can this be merged now?

2018-02-12 00:17 UTC, sevein approved these changes
Small cosmetic suggestion but I think it could be fixed later if we're in a rush. 👍

2018-02-12 00:17 UTC, sevein commented on README.md
> +The default Archivematica install relies on ElasticSearch for different features (Archival storage, Backlog and Appraisal tabs). If you need to disable them, the role variable `archivematica_src_sear
s/ElasticSearch/Elasticsearch

2018-02-14 00:12 UTC, merged

2018-02-14 00:13 UTC, jrwdunham commented
I fixed the typo. I also used this role in a deploy-pub Vagrant deploy and confirmed it can be used to correctly deploy AM headlessly. See https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/67#issuecomment-365447477.