pipeline-es: Add ES index mappings workaround
artefactual-labs/ansible-role-archivematica-src pull request #242
Opened 2019-04-05 16:45 UTC by mamedin

This commit adds the workaround for issue:

https://github.com/archivematica/Issues/issues/608

It is is needed when upgrading from AM v1.9.0.

The `archivematica_src_search_enabled` variable can be set as:

- true
- yes
- all
- false
- aips
- transfers

That's the reason why aips and transfers indices are checked
individually and there are 2 separate tasks to add the workaround for
transfers and aips.

2019-04-10 09:04 UTC, scollazo requested changes

2019-04-10 09:04 UTC, scollazo commented on tasks/pipeline-es.yml
> +      body: "{ \"index.mapping.total_fields.limit\": 10000, \"index.mapping.depth.limit\": 1000 }"
I think we should create a new variable instead of hardcoding 1000...

2019-05-23 16:12 UTC, scollazo commented
@mamedin any news about this?

2019-05-23 16:14 UTC, mamedin commented
@scollazo fixed here: https://github.com/artefactual/archivematica/pull/1388

2019-05-23 16:14 UTC, mamedin commented
I think we can close this issue.

2019-05-24 01:21 UTC, closed without merging