Allow for mysql configuration for SS
artefactual-labs/ansible-role-archivematica-src pull request #259
Opened 2019-10-10 10:52 UTC by scollazo

Related to https://github.com/archivematica/Issues/issues/931

2019-10-10 10:52 UTC, scollazo commented
This is intended to be merged after #258

2019-10-22 14:46 UTC, mamedin requested changes

2019-10-22 14:46 UTC, mamedin commented on tasks/configure.yml
> +    chdir: "{{ archivematica_src_ss_app }}"
Hi @scollazo we have an old typo on this variable:
```
maml@molinillo ~/external-roles/artefactual-archivematica-qa-src $ grep -Ri archviematica_src_ss_app *
tasks/configure.yml:    chdir: "{{ archviematica_src_ss_app }}"
tasks/configure.yml:    app_path: "{{ archviematica_src_ss_app }}"
tasks/ss-main.yml:      dest: "{{ archviematica_src_ss_app }}"
tasks/ss-main.yml:    app_path: "{{ archviematica_src_ss_app }}"
tasks/ss-db.yml:    app_path: "{{ archviematica_src_ss_app }}"
tasks/ss-db.yml:    app_path: "{{ archviematica_src_ss_app }}"
templates/etc/systemd/system/archivematica-storage-service.service.j2:WorkingDirectory={{ archviematica_src_ss_app }}
vars/main.yml:archviematica_src_ss_app: "/usr/lib/archivematica/storage-service"
``` 
So we can continue using the ` archviematica_src_ss_app` var or fix the typo.

2019-10-22 14:47 UTC, mamedin commented on tasks/configure.yml
> +    chdir: "{{ archivematica_src_ss_app }}"
Same issue here

2019-11-12 21:56 UTC, mamedin approved these changes
LGTM!

2019-11-29 12:36 UTC, merged