Add ability to configure locations in the default SS space
artefactual-labs/ansible-role-archivematica-src pull request #262
Opened 2019-12-05 14:45 UTC by scollazo

2019-12-05 14:46 UTC, scollazo commented
This pr is built on top of #261

2019-12-09 19:00 UTC, mamedin requested changes

2019-12-09 19:00 UTC, mamedin commented on tasks/configure.yml
> +    - name: "Configure SS: add NFS location: {{ item.location_description }}"
Hi Santi, the PR looks fine, but I think we need a cosmetic change. This task name should be more generic, something like "Configure SS: add custom locations". The `{{ item.location_description }}` is not changed to its value on every iteration, so we can remote it from name:

```
TASK [external-roles/artefactual-archivematica-src-mysql : Configure SS: add NFS location: {{ item.location_description }}] ************************************************************************
ok: [mamedin-bionic-PR261] => (item={u'location_path': u'/replicator', u'location_purpose': u'RP', u'location_description': u'Replicator location', u'location_default': u'false'})
ok: [mamedin-bionic-PR261] => (item={u'location_path': u'/aipstore', u'location_purpose': u'AS', u'location_description': u'AipStore', u'location_default': u'true'})
ok: [mamedin-bionic-PR261] => (item={u'location_path': u'/transfer-source/', u'location_purpose': u'TS', u'location_description': u'Transfer Source', u'location_default': u'false'})
```

2019-12-09 19:07 UTC, mamedin commented on tasks/configure.yml
> +    - name: "Configure SS: add NFS location: {{ item.location_description }}"
```suggestion
    - name: "Configure SS: add custom locations"
```

2019-12-09 19:14 UTC, mamedin approved these changes
LGTM

2019-12-09 19:20 UTC, merged