Update Node.js tasks for Debian
artefactual-labs/ansible-role-archivematica-src pull request #402
Opened 2024-06-25 13:01 UTC by replaceafill

This updates the repository used for installing Node.js in Debian distributions and removes the `nodejs_version` variable from the `vars` directory so it can be overridden from playbooks.

Connected to https://github.com/artefactual-labs/ansible-archivematica-src/issues/400
Connected to https://github.com/artefactual-labs/ansible-archivematica-src/issues/401

2024-06-25 17:01 UTC, mamedin requested changes
I think we need to add  nodejs_version to defauls/main.yml

2024-06-25 17:04 UTC, replaceafill commented
> I think we need to add nodejs_version to defauls/main.yml

Should we move it from `vars/main.yml`? Or duplicate it?

2024-06-25 17:10 UTC, mamedin commented
> > I think we need to add nodejs_version to defauls/main.yml
> 
> Should we move it from `vars/main.yml`? Or duplicate it?

Nah, that's perfect!

2024-06-25 17:10 UTC, mamedin approved these changes
LGTM! Thanks

2024-06-25 17:11 UTC, merged

2024-06-26 16:52 UTC, replaceafill commented
Cherry-picked to `stable/1.16.x`:
* https://github.com/artefactual-labs/ansible-archivematica-src/commit/bde75afae9fa5fe8dcb86fafd4700ee408940391
* https://github.com/artefactual-labs/ansible-archivematica-src/commit/d98e0383b142a7582282b0e28d169d2ca1385ad2